require_relative 'executor'

TYPE = ENV['TYPE']
CODE_PATH=ENV['CODE_PATH']

describe 'Challenge 5' do
  before do
    @executor = Executor.new(TYPE, CODE_PATH)
  end

  CASES = [
    [['Hello'], "H\ne\nl\nl\no"],
    [[''], ""],
    [['Hello', 'World'], "HW\neo\nlr\nll\nod"],
    [['I', 'am', 'new', 'here'], "Ianh\n mee\n  wr\n   e"],
    # Executor removes trailing whitespace, so no spaces at the end of expected results.
    # Also, sending an empty string so that it will be interpreted by the console.
    [["I", "have", '""', "to", "say"], "Ih ts\n a oa\n v  y\n e" ],
    [['One', 'ring', 'to', 'rule', 'them', 'all'], "Ortrta\nniouhl\nen lel\n g em"],
    [['Lost', 'a', 'planet', 'Obi-Wan', 'has'],
      "LapOh\no lba\ns ais\nt n- \n  eW \n  ta \n   n" ]
  ]

  RANDOM_CASES = [
    [["anion", "smirk", "hater", "naiads"], "ashn\nnmaa\niiti\norea\nnkrd\n   s"],
    [["snails", "Hasbro", "wept", "hats"], "sHwh\nnaea\naspt\nibts\nlr  \nso"],
    [["playboy", "frugal", "Burgess", "excite"], "pfBe\nlrux\naurc\nyggi\nbaet\nolse\ny s"],
    [["larynx", "settle", "contour", "scythes"], "lscs\naeoc\nrtny\nyttt\nnloh\nxeue\n  rs"],
    [["pings", "tent", "thief", "glided"], "pttg\niehl\nnnii\ngted\ns fe\n   d"],
    [["saltier", "jested", "tapered", "reffing"], "sjtr\naeae\nlspf\nttef\nieri\neden\nr dg"],
    [["hook", "serape", "Ortega", "wilful"], "hsOw\noeri\nortl\nkaef\n pgu\n eal"],
    [["islets", "June", "killing", "Pawnee"], "iJkP\nsuia\nlnlw\neeln\nt ie\ns ne\n  g"],
    [["funkier", "Bowell", "Ford", "Fahd"], "fBFF\nuooa\nnwrh\nkedd\nil  \nel  \nr"],
    [["slate", "meanly", "ukulele", "codding"], "smuc\nleko\naaud\ntnld\nelei\n yln\n  eg"],
    [["marlin", "shads", "tousled", "gardens"], "mstg\nahoa\nraur\nldsd\nisle\nn en\n  ds"],
    [["rewords", "assured", "render", "Eli"], "rarE\nesel\nwsni\noud \nrre \nder \nsd"],
    [["refill", "flaps", "poised", "mottos"], "rfpm\neloo\nfait\nipst\nlseo\nl ds"],
    [["knob", "mavins", "Crux", "spinal"], "kmCs\nnarp\novui\nbixn\n n a\n s l"],
    [["hordes", "stoned", "clop", "visages"], "hscv\notli\nroos\ndnpa\nee g\nsd e\n   s"],
    [["staider", "bonnet", "elitism", "raunchy"], "sber\ntola\naniu\nintn\ndeic\netsh\nr my"],
    [["crudely", "livery", "pursuer", "Amway"], "clpA\nrium\nuvrw\ndesa\neruy\nlye \ny r"],
    [["doctor", "schlock", "biggie", "Ijssel"], "dsbI\nocij\nchgs\ntlgs\nooie\nrcel\n k"],
    [["flakes", "wry", "Lyly", "tatter"], "fwLt\nlrya\naylt\nk yt\ne  e\ns  r"],
    [["pale", "maizes", "tarps", "duffers"], "pmtd\naaau\nlirf\nezpf\n ese\n s r\n   s"],
    [["middies", "account", "rimming", "burgeon"], "marb\niciu\ndcmr\ndomg\niuie\nenno\nstgn"],
    [["crowbar", "balling", "Maurice", "yelled"], "cbMy\nraae\nolul\nwlrl\nbiie\nancd\nrge"],
    [["yew", "Merton", "Monday", "Zwingli"], "yMMZ\neeow\nwrni\n tdn\n oag\n nyl\n   i"],
    [["femurs", "coaxing", "vegan", "Norway"], "fcvN\neoeo\nmagr\nuxaw\nrina\nsn y\n g"],
    [["autism", "canard", "mangos", "forging"], "acmf\nuaao\ntnnr\niagg\nsroi\nmdsn\n   g"],
    [["pry", "plumped", "visits", "Nokia"], "ppvN\nrlio\nyusk\n mii\n pta\n es \n d"],
    [["forging", "infer", "stills", "hell"], "fish\nonte\nrfil\ngell\nirl \nn s \ng"],
    [["battles", "learn", "warship", "tremors"], "blwt\naear\ntare\ntrsm\nlnho\ne ir\ns ps"],
    [["Eton", "dodder", "fakers", "Karroo"], "EdfK\ntoaa\nodkr\nnder\n ero\n rso"],
    [["tarring", "tweeted", "Danny", "Sumeria"], "ttDS\nawau\nrenm\nrene\nityr\nne i\ngd a"],
    [["Capra", "moderns", "crazing", "reclaim"], "Cmcr\naore\npdac\nrezl\naria\n nni\n sgm"],
    [["destiny", "fragile", "cuddles", "filter"], "dfcf\nerui\nsadl\ntgdt\niile\nnler\nyes"],
    [["Rhenish", "wimple", "weedy", "Esq"], "RwwE\nhies\nemeq\nnpd \nily \nse  \nh"],
    [["potshot", "Beryl", "pompon", "alined"], "pBpa\noeol\ntrmi\nsypn\nhloe\no nd\nt"],
    [["ossify", "bode", "banter", "Archie"], "obbA\nsoar\nsdnc\nieth\nf ei\ny re"],
    [["nowhere", "thrive", "smite", "pokiest"], "ntsp\nohmo\nwrik\nhiti\nevee\nre s\ne  t"],
    [["joggled", "calling", "Mongols", "emboss"], "jcMe\noaom\nglnb\nglgo\nlios\nenls\ndgs"],
    [["peeks", "escrows", "canoed", "Ruiz"], "pecR\nesau\necni\nkroz\nsoe \n wd \n s"],
    [["hapless", "skipper", "Debian", "rackets"], "hsDr\nakea\npibc\nlpik\nepae\nsent\nsr s"],
    [["roaches", "compare", "parity", "mortar"], "rcpm\nooao\namrr\ncpit\nhata\neryr\nse"],
    [["begins", "girth", "Hattie", "Seebeck"], "bgHS\neiae\ngrte\nittb\nnhie\ns ec\n   k"],
    [["riddled", "victual", "wrap", "jumbles"], "rvwj\niiru\ndcam\ndtpb\nlu l\nea e\ndl s"],
    [["dabbing", "cornets", "bagging", "salmon"], "dcbs\naoaa\nbrgl\nbngm\nieio\nntnn\ngsg"],
    [["flits", "advents", "raja", "proviso"], "farp\nldar\nivjo\nteav\nsn i\n t s\n s o"],
    [["pharaoh", "kabobs", "prize", "Freda"], "pkpF\nharr\nabie\nrozd\nabea\nos  \nh"],
    [["steep", "Tahiti", "Tlaloc", "brisk"], "sTTb\ntalr\nehai\neils\nptok\n ic"],
    [["barge", "designs", "Amparo", "betas"], "bdAb\naeme\nrspt\ngiaa\negrs\n no \n s"],
    [["bacon", "Pontiac", "verbals", "Jaguar"], "bPvJ\naoea\ncnrg\notbu\nniaa\n alr\n cs"],
    [["lacked", "jerkin", "portion", "pshaw"], "ljpp\naeos\ncrrh\nkkta\neiiw\ndno \n  n"],
    [["gaiters", "sierra", "Cesar", "fizz"], "gsCf\naiei\niesz\ntraz\nerr \nra  \ns"],
    [["spates", "gofers", "allergy", "pates"], "sgap\npola\naflt\nteee\nerrs\nssg \n  y"],
    [["emcee", "solaced", "dealers", "Valois"], "esdV\nmoea\nclal\nealo\necei\n ers\n ds"],
    [["dodo", "slimmer", "safest", "simmers"], "dsss\nolai\ndifm\nomem\n mse\n etr\n r s"],
    [["laps", "asexual", "loyally", "Naipaul"], "lalN\nasoa\npeyi\nsxap\n ula\n alu\n lyl"],
    [["servers", "cryings", "affixes", "breeder"], "scab\nerfr\nryfe\nviie\nenxd\nrgee\nsssr"],
    [["rum", "Ellie", "rapine", "usher"], "rEru\nulas\nmlph\n iie\n enr\n  e"],
    [["guano", "Catalan", "bootie", "savors"], "gCbs\nuaoa\natov\nnato\nolir\n aes\n n"],
    [["emirs", "Elwood", "trisect", "guess"], "eEtg\nmlru\niwie\nross\nsoes\n dc \n  t"],
    [["Lassen", "second", "hemp", "barker"], "Lshb\naeea\nscmr\nsopk\nen e\nnd r"],
    [["planar", "lignite", "diploma", "crowds"], "pldc\nliir\nagpo\nnnlw\naiod\nrtms\n ea"],
    [["Astana", "Stevens", "seniors", "Patna"], "ASsP\nstea\ntent\navin\nneoa\nanr \n ss"],
    [["ovules", "runners", "muscat", "grapnel"], "ormg\nvuur\nunsa\nlncp\neean\nsrte\n s l"],
    [["Danial", "bulimic", "mantled", "disuses"], "Dbmd\nauai\nnlns\niitu\namls\nliee\n cds"],
    [["Bud", "frills", "subdued", "crag"], "Bfsc\nurur\ndiba\n ldg\n lu \n se \n  d"],
    [["synches", "urinary", "tassel", "pricked"], "sutp\nyrar\nnisi\ncnsc\nhaek\nerle\nsy d"],
    [["Kruger", "Qatar", "graven", "doctors"], "KQgd\nraro\nutac\ngavt\nereo\nr nr\n   s"],
    [["yuppie", "callus", "momma", "macadam"], "ycmm\nuaoa\nplmc\nplma\niuad\nes a\n   m"],
    [["tinted", "Berg", "trig", "pail"], "tBtp\niera\nnrii\ntggl\ne   \nd"],
    [["rectors", "canyon", "repulse", "albumen"], "rcra\neael\ncnpb\ntyuu\noolm\nrnse\ns en"],
    [["Carina", "Alioth", "council", "kinda"], "CAck\naloi\nriun\niond\nntca\nahi \n  l"],
    [["Lamarck", "panoply", "ohms", "hated"], "Lpoh\naaha\nmnmt\naose\nrp d\ncl  \nky"],
    [["Luce", "uvula", "frolics", "Luzon"], "LufL\nuvru\ncuoz\nello\n ain\n  c \n  s"],
    [["stiffen", "regatta", "Feb", "mulls"], "srFm\nteeu\nigbl\nfa l\nft s\net  \nna"],
    [["poured", "Nevis", "brittle", "guzzle"], "pNbg\noeru\nuviz\nritz\nestl\nd le\n  e"],
    [["reverse", "whammed", "autumn", "Sony"], "rwaS\nehuo\nvatn\nemuy\nrmm \nsen \ned"],
    [["unknown", "Suva", "boxcars", "Armour"], "uSbA\nnuor\nkvxm\nnaco\no au\nw rr\nn s"],
    [["blurbs", "trawler", "step", "Atria"], "btsA\nlrtt\nuaer\nrwpi\nbl a\nse  \n r"],
    [["Verna", "Walton", "pout", "Omahas"], "VWpO\neaom\nrlua\nntth\nao a\n n s"],
    [["Capra", "Schmidt", "weds", "animal"], "CSwa\nacen\nphdi\nrmsm\nai a\n d l\n t"],
    [["House", "Byron", "treeing", "Rhode"], "HBtR\noyrh\nureo\nsoed\nenie\n  n \n  g"],
    [["Baptist", "Shaula", "thefts", "vend"], "BStv\nahhe\npaen\ntufd\nilt \nsas \nt"],
    [["Holt", "Rex", "twiggy", "tsarina"], "HRtt\noews\nlxia\nt gr\n  gi\n  yn\n   a"],
    [["cants", "amirs", "mussel", "suntan"], "cams\namuu\nnisn\ntrst\nssea\n  ln"],
    [["Pilate", "gadgets", "nice", "beasts"], "Pgnb\niaie\nldca\nages\nte t\net s\n s"],
    [["votive", "divers", "filched", "dross"], "vdfd\noiir\ntvlo\niecs\nvrhs\nese \n  d"],
    [["bonnets", "smog", "witched", "catarrh"], "bswc\nomia\nnott\nngca\ne hr\nt er\ns dh"],
    [["nope", "crapes", "braids", "Genaro"], "ncbG\norre\npaan\nepia\n edr\n sso"],
    [["stumpy", "beefy", "Aurelia", "glimmer"], "sbAg\nteul\nueri\nmfem\npylm\ny ie\n  ar"],
    [["gulled", "Hakluyt", "Perkins", "belt"], "gHPb\nuaee\nlkrl\nllkt\neui \ndyn \n ts"],
    [["rodent", "reeves", "owlet", "Jewell"], "rroJ\noewe\ndelw\nevee\nnetl\nts l"],
    [["Berta", "schemes", "firs", "prude"], "Bsfp\necir\nrhru\ntesd\nam e\n e  \n s"],
    [["grog", "Sonya", "package", "thrifts"], "gSpt\nroah\noncr\ngyki\n aaf\n  gt\n  es"],
    [["chammy", "fellow", "posh", "ashed"], "cfpa\nheos\nalsh\nmlhe\nmo d\nyw"],
    [["dowel", "anchovy", "comas", "misplay"], "dacm\nonoi\nwcms\nehap\nlosl\n v a\n y y"],
    [["jading", "Diego", "sputum", "garbled"], "jDsg\naipa\ndeur\nigtb\nnoul\ng me\n   d"],
    [["punters", "lions", "snooker", "Morse"], "plsM\nuino\nnoor\ntnos\neske\nr e \ns r"],
    [["attain", "began", "juggle", "navels"], "abjn\nteua\ntggv\naage\ninll\nn es"],
    [["sames", "cloture", "timbres", "sachets"], "scts\nalia\nmomc\netbh\nsure\n ret\n ess"],
    [["flints", "poxes", "agog", "scrota"], "fpas\nlogc\nixor\nnego\nts t\ns  a"],
    [["peers", "saxes", "tine", "barbers"], "pstb\neaia\nexnr\nreeb\nss e\n   r\n   s"],
    [["mites", "Olmsted", "anchors", "Yacc"], "mOaY\nilna\ntmcc\neshc\nsto \n er \n ds"],
    [["emoted", "Onsager", "twos", "Carrier"], "eOtC\nmnwa\nosor\ntasr\neg i\nde e\n r r"],
    [["douse", "clank", "treats", "cosign"], "dctc\nolro\nuaes\nsnai\nektg\n  sn"],
    [["chafing", "welshed", "spray", "Plath"], "cwsP\nhepl\nalra\nfsat\nihyh\nne  \ngd"],
    [["Nabisco", "freebie", "swishes", "Fresnel"], "NfsF\narwr\nbeie\niess\nsbhn\nciee\noesl"],
    [["moths", "crystal", "madness", "gamma"], "mcmg\noraa\ntydm\nhsnm\nstea\n as \n ls"],
    [["tumbler", "resend", "crushed", "expunge"], "trce\nuerx\nmsup\nbesu\nlnhn\nedeg\nr de"],
    [["Lauren", "eighths", "museum", "Segre"], "LemS\naiue\nugsg\nrher\netue\nnhm \n s"],
    [["knifes", "ratty", "tidbits", "starred"], "krts\nnait\nitda\nftbr\neyir\ns te\n  sd"],
    [["Krystal", "gases", "solved", "mapped"], "Kgsm\nraoa\nyslp\nsevp\ntsee\na dd\nl"],
    [["septets", "Coulomb", "Prakrit", "scalps"], "sCPs\neorc\npuaa\ntlkl\neorp\ntmis\nsbt"],
    [["leanest", "foxing", "will", "sinking"], "lfws\neoii\naxln\nnilk\nen i\nsg n\nt  g"],
    [["Greece", "mourned", "mindful", "flouts"], "Gmmf\nroil\neuno\nerdu\ncnft\neeus\n dl"],
    [["agar", "Schwinn", "grownup", "smacks"], "aSgs\ngcrm\nahoa\nrwwc\n ink\n nus\n np"],
    [["density", "unseals", "Anabel", "Bierce"], "duAB\nenni\nnsae\nsebr\niaec\ntlle\nys"],
    [["swished", "Jerri", "belongs", "gurgles"], "sJbg\nweeu\nirlr\nsrog\nhinl\ne ge\nd ss"],
    [["dimmed", "Rusty", "hellos", "leftist"], "dRhl\niuee\nmslf\nmtlt\neyoi\nd ss\n   t"],
    [["floozy", "grabber", "togas", "crowned"], "fgtc\nlror\noago\nobaw\nzbsn\nye e\n r d"],
    [["slyer", "Angora", "porn", "softie"], "sAps\nlnoo\nygrf\neont\nrr i\n a e"],
    [["pitch", "Lizzy", "bogy", "aerated"], "pLba\niioe\ntzgr\nczya\nhy t\n   e\n   d"],
    [["mavins", "joggle", "tombs", "blankly"], "mjtb\naool\nvgma\nigbn\nnlsk\nse l\n   y"],
    [["zircon", "Nepal", "Kilauea", "dew"], "zNKd\nieie\nrplw\ncaa \nolu \nn e \n  a"],
    [["Tull", "nowhere", "rancher", "Sedna"], "TnrS\nuoae\nlwnd\nlhcn\n eha\n re \n er"],
    [["pining", "Orizaba", "coups", "praised"], "pOcp\niror\nniua\nizpi\nnass\ngb e\n a d"],
    [["dials", "hailed", "rapped", "jousted"], "dhrj\niaao\naipu\nllps\nseet\n dde\n   d"],
    [["posed", "jitneys", "woolier", "maria"], "pjwm\noioa\nstor\nenli\ndeia\n ye \n sr"],
    [["chantey", "duchies", "tiled", "fossil"], "cdtf\nhuio\nacls\nnhes\ntidi\nee l\nys"],
    [["erectly", "oblong", "mantels", "Templar"], "eomT\nrbae\nelnm\ncotp\ntnel\nlgla\ny sr"],
    [["Yeager", "paunchy", "stagger", "equal"], "Ypse\neatq\nauau\ngnga\necgl\nrhe \n yr"],
    [["addenda", "balls", "lawsuit", "sheller"], "abls\ndaah\ndlwe\nelsl\nnsul\nd ie\na tr"],
    [["troika", "Wiley", "burrs", "urns"], "tWbu\nriur\nolrn\niers\nkys \na"],
    [["embroil", "barren", "pH", "fobs"], "ebpf\nmaHo\nbr b\nrr s\noe  \nin  \nl"],
    [["damaged", "misstep", "fibroid", "defect"], "dmfd\naiie\nmsbf\nasre\ngtoc\neeit\ndpd"],
    [["crating", "unseats", "Rolaids", "hypo"], "cuRh\nrnoy\naslp\nteao\niai \nntd \ngss"],
    [["alleys", "pilot", "Susanne", "Hudson"], "apSH\nliuu\nllsd\neoas\nytno\ns nn\n  e"],
    [["Midland", "apple", "thrice", "porter"], "Matp\nipho\ndprr\nllit\naece\nn er\nd"],
    [["agenda", "weaker", "land", "eves"], "awle\ngeav\neane\nnkds\nde  \nar"],
    [["disowns", "Onegin", "Emanuel", "lower"], "dOEl\ninmo\nseaw\nogne\nwiur\nnne \ns l"],
    [["strokes", "knave", "urgency", "snores"], "skus\ntnrn\nrago\nover\nkene\ne cs\ns y"],
    [["galling", "assured", "Savage", "pasty"], "gaSp\nasaa\nlsvs\nluat\nirgy\nnee \ngd"],
    [["Quezon", "rammed", "bitchy", "variant"], "Qrbv\nuaia\nemtr\nzmci\noeha\nndyn\n   t"],
    [["beg", "clashed", "trucker", "drowse"], "bctd\nelrr\ngauo\n scw\n hks\n eee\n dr"],
    [["vibes", "Ob", "neat", "peerage"], "vOnp\nibee\nb ae\ne tr\ns  a\n   g\n   e"],
    [["dean", "vanning", "maunder", "elegant"], "dvme\neaal\nanue\nnnng\n ida\n nen\n grt"],
    [["poked", "dustman", "wile", "crud"], "pdwc\nouir\nkslu\neted\ndm  \n a  \n n"],
    [["Spaatz", "Augean", "wharf", "ridging"], "SAwr\npuhi\nagad\naerg\ntafi\nzn n\n   g"],
    [["license", "Benton", "cots", "assumes"], "lBca\nieos\ncnts\netsu\nno m\nsn e\ne  s"],
    [["hiccups", "carfare", "bending", "forests"], "hcbf\niaeo\ncrnr\ncfde\nuais\nprnt\nsegs"],
    [["fuchsia", "Jay", "mailbox", "raping"], "fJmr\nuaaa\ncyip\nh li\ns bn\ni og\na x"],
    [["pita", "breathy", "douses", "wincing"], "pbdw\niroi\nteun\naasc\n tei\n hsn\n y g"],
    [["berried", "reeving", "genetic", "foul"], "brgf\neeeo\nrenu\nrvel\niit \neni \ndgc"],
    [["pipping", "unplugs", "silted", "gamut"], "pusg\ninia\npplm\npltu\niuet\nngd \ngs"],
    [["maxes", "saith", "Colbert", "bank"], "msCb\naaoa\nxiln\netbk\nshe \n  r \n  t"],
    [["kernels", "newer", "holdout", "Dylan"], "knhD\neeoy\nrwll\nneda\neron\nl u \ns t"],
    [["sofa", "cooties", "tolled", "Shelley"], "sctS\noooh\nfole\natll\n iel\n ede\n s y"],
    [["Terra", "bestirs", "radars", "squabs"], "Tbrs\neeaq\nrsdu\nrtaa\nairb\n rss\n s"],
    [["fatten", "yelps", "karats", "caste"], "fykc\naeaa\ntlrs\ntpat\neste\nn s"],
    [["fires", "hubcap", "trinket", "quavery"], "fhtq\niuru\nrbia\necnv\nsake\n per\n  ty"],
    [["gobbler", "laded", "goings", "daily"], "glgd\noaoa\nbdii\nbenl\nldgy\ne s \nr"],
    [["Mulder", "Enid", "Parrish", "Holley"], "MEPH\nunao\nlirl\nddrl\ne ie\nr sy\n  h"],
    [["Sibyl", "soils", "coping", "eroding"], "Ssce\nioor\nbipo\nylid\nlsni\n  gn\n   g"],
    [["migrant", "felony", "haft", "clouted"], "mfhc\nieal\nglfo\nrotu\nan t\nny e\nt  d"],
    [["Babels", "wistful", "enraged", "deiced"], "Bwed\naine\nbsri\netac\nlfge\nsued\n ld"],
    [["foetus", "biased", "cribbed", "Lisbon"], "fbcL\noiri\neais\ntsbb\nuebo\nsden\n  d"],
    [["inmates", "tents", "erosive", "blazed"], "iteb\nnerl\nmnoa\natsz\ntsie\ne vd\ns e"],
    [["styling", "aught", "whoopee", "Mazama"], "sawM\ntuha\nygoz\nlhoa\nitpm\nn ea\ng e"],
    [["bases", "commons", "Barnett", "humerus"], "bcBh\naoau\nsmrm\nemne\nsoer\n ntu\n sts"],
    [["clotted", "plucks", "Florine", "cleanse"], "cpFc\nllll\nouoe\ntcra\ntkin\nesns\nd ee"],
    [["thumb", "nautili", "sillier", "bobbles"], "tnsb\nhaio\nuulb\nmtlb\nbiil\n lee\n irs"],
    [["defend", "request", "Regina", "riskier"], "drRr\neeei\nfqgs\neuik\nneni\ndsae\n t r"],
    [["eighty", "caroms", "maced", "discoed"], "ecmd\niaai\ngrcs\nhoec\ntmdo\nys e\n   d"],
    [["muffled", "galling", "malls", "spy"], "mgms\nuaap\nflly\nfll \nlis \nen  \ndg"],
    [["Tupi", "radio", "beckon", "valid"], "Trbv\nuaea\npdcl\niiki\n ood\n  n"],
    [["sided", "starlet", "enraged", "enrage"], "ssee\nitnn\ndarr\neraa\ndlgg\n eee\n td"],
    [["German", "needier", "famous", "Aymara"], "GnfA\neeay\nremm\nmdoa\naiur\nnesa\n r"],
    [["Nero", "trod", "avails", "looser"], "Ntal\nervo\nroao\nodis\n  le\n  sr"],
    [["feel", "butlers", "arid", "riot"], "fbar\neuri\netio\nlldt\n e  \n r  \n s"],
    [["blab", "thank", "cream", "flailed"], "btcf\nlhrl\naaea\nbnai\n kml\n   e\n   d"],
    [["piker", "cutesy", "direr", "Freddy"], "pcdF\niuir\nktre\neeed\nrsrd\n y y"],
    [["Clorox", "orbs", "ring", "plumbs"], "Corp\nlril\nobnu\nrsgm\no  b\nx  s"],
    [["tightly", "bounds", "canoed", "thugs"], "tbct\nioah\ngunu\nhnog\ntdes\nlsd \ny"],
    [["Fuchs", "heifer", "Camoens", "fiches"], "FhCf\nueai\ncimc\nhfoh\nseee\n rns\n  s"],
    [["asks", "Frazier", "jitney", "mitt"], "aFjm\nsrii\nkatt\nsznt\n ie \n ey \n r"],
    [["unsold", "Lea", "Beowulf", "chit"], "uLBc\nneeh\nsaoi\no wt\nl u \nd l \n  f"],
    [["spread", "Balboa", "avarice", "Gauss"], "sBaG\npava\nrlau\nebrs\naois\ndac \n  e"],
    [["Es", "anvils", "Dobbin", "Plato"], "EaDP\nsnol\n vba\n ibt\n lio\n sn"],
    [["antic", "Eliot", "Pogo", "combats"], "aEPc\nnloo\ntigm\nioob\nct a\n   t\n   s"],
    [["induced", "prone", "Nunki", "ripe"], "ipNr\nnrui\ndonp\nunke\ncei \ne   \nd"],
    [["Quayle", "styli", "dulcet", "sandlot"], "Qsds\nutua\nayln\nylcd\nliel\ne to\n   t"],
    [["cranial", "Kiwanis", "delis", "seduced"], "cKds\nriee\nawld\nnaiu\ninsc\nai e\nls d"],
    [["capitol", "shrinks", "rifled", "imparts"], "csri\nahim\nprfp\niila\ntner\nokdt\nls s"],
    [["natty", "bombers", "kept", "chiefer"], "nbkc\naoeh\ntmpi\ntbte\nye f\n r e\n s r"],
    [["twinge", "sidle", "largess", "crawl"], "tslc\nwiar\nidra\nnlgw\ngeel\ne s \n  s"],
    [["density", "brawn", "caviled", "rebuts"], "dbcr\nerae\nnavb\nswiu\ninlt\nt es\ny d"],
    [["sox", "Dijon", "marauds", "washers"], "sDmw\noiaa\nxjrs\n oah\n nue\n  dr\n  ss"],
    [["twig", "autos", "nimbus", "stead"], "tans\nwuit\nitme\ngoba\n sud\n  s"],
    [["ism", "cadger", "babbles", "savor"], "icbs\nsaaa\nmdbv\n gbo\n elr\n re \n  s"],
    [["Zuni", "bleak", "stirs", "Brahmin"], "ZbsB\nultr\nneia\niarh\n ksm\n   i\n   n"],
    [["medleys", "niacin", "creaky", "eulogy"], "mnce\neiru\ndael\nlcao\neikg\nynyy\ns"],
    [["sowers", "Lesa", "mister", "tweet"], "sLmt\noeiw\nwsse\neate\nr et\ns r"],
    [["Romanov", "caste", "prowler", "sledge"], "Rcps\noarl\nmsoe\natwd\nnelg\no ee\nv r"],
    [["frontal", "hussar", "sloes", "cache"], "fhsc\nrula\nosoc\nnseh\ntase\nar  \nl"],
    [["prepare", "peewees", "hectic", "fabrics"], "pphf\nreea\neecb\npwtr\naeii\nrecc\nes s"],
    [["driver", "cranks", "Daimler", "strait"], "dcDs\nrrat\niair\nvnma\nekli\nrset\n  r"],
    [["Cretan", "brogue", "drool", "emails"], "Cbde\nrrrm\neooa\ntgoi\naull\nne s"],
    [["evinces", "madders", "writ", "Reunion"], "emwR\nvare\nidiu\nndtn\nce i\ner o\nss n"],
    [["stain", "rimming", "More", "affix"], "srMa\ntiof\namrf\nimei\nni x\n n  \n g"],
    [["Hockney", "crapes", "Benito", "tubs"], "HcBt\noreu\ncanb\nkpis\nnet \neso \ny"],
    [["flung", "East", "engross", "Minot"], "fEeM\nlani\nusgn\nntro\ng ot\n  s \n  s"],
    [["behinds", "flocks", "sully", "joules"], "bfsj\neluo\nholu\nicll\nnkye\nds s\ns"],
    [["petrify", "granary", "piecing", "whoosh"], "pgpw\nerih\ntaeo\nrnco\niais\nfrnh\nyyg"],
    [["Kendall", "maws", "smart", "brushes"], "Kmsb\neamr\nnwau\ndsrs\na th\nl  e\nl  s"],
    [["Lyons", "dories", "buffoon", "brigs"], "Ldbb\nyour\norfi\nnifg\nseos\n so \n  n"],
    [["Judson", "pits", "clocked", "grabbed"], "Jpcg\nuilr\ndtoa\nsscb\no kb\nn ee\n  dd"],
    [["Zane", "dodgers", "Lucian", "assuage"], "ZdLa\naous\nndcs\negiu\n eaa\n rng\n s e"],
    [["doggy", "asylums", "cadence", "Orbison"], "dacO\nosar\ngydb\nglei\nyuns\n mco\n sen"],
    [["humid", "Lakisha", "routed", "might"], "hLrm\nuaoi\nmkug\niith\ndset\n hd \n a"],
    [["totter", "quicken", "plot", "Baroda"], "tqpB\noula\ntior\ntcto\nek d\nre a\n n"],
    [["ism", "gypped", "slating", "awls"], "igsa\nsylw\nmpal\n pts\n ei \n dn \n  g"],
    [["also", "scubaed", "Tahoe", "pacts"], "asTp\nlcaa\nsuhc\nobot\n aes\n e  \n d"],
    [["portals", "wet", "jaws", "Ruby"], "pwjR\noeau\nrtwb\nt sy\na   \nl   \ns"],
    [["zoom", "shelled", "Alfonso", "clot"], "zsAc\nohll\noefo\nmlot\n ln \n es \n do"],
    [["Adana", "cicadae", "snap", "nodules"], "Acsn\ndino\nacad\nnapu\nad l\n a e\n e s"],
    [["ended", "viols", "noels", "deeming"], "evnd\nnioe\ndoee\nellm\ndssi\n   n\n   g"],
    [["bride", "Nola", "chitin", "zincing"], "bNcz\nrohi\nilin\ndatc\ne ii\n  nn\n   g"],
    [["Durante", "Oahu", "Marla", "zone"], "DOMz\nuaao\nrhrn\naule\nn a \nt   \ne"],
    [["attune", "edited", "clown", "hazels"], "aech\ntdla\ntioz\nutwe\nnenl\ned s"],
    [["lorded", "auspice", "Advent", "perigee"], "laAp\noude\nrsvr\ndpei\neing\ndcte\n e e"],
    [["faraway", "shrines", "tours", "jerks"], "fstj\nahoe\nrrur\nairk\nwnss\nae  \nys"],
    [["subplot", "redoes", "chunky", "hitched"], "srch\nuehi\nbdut\nponc\nlekh\nosye\nt  d"],
    [["french", "Octavia", "lop", "pitying"], "fOlp\nrcoi\netpt\nna y\ncv i\nhi n\n a g"],
    [["spacey", "Liza", "nix", "Garza"], "sLnG\npiia\nazxr\nca z\ne  a\ny"],
    [["peso", "recruit", "laths", "styptic"], "prls\neeat\nscty\norhp\n ust\n i i\n t c"],
    [["Algenib", "Kelsey", "Randal", "outer"], "AKRo\nleau\nglnt\nesde\nnear\niyl \nb"],
    [["pistols", "thud", "honks", "Fredric"], "pthF\nihor\nsune\ntdkd\no sr\nl  i\ns  c"],
    [["mummery", "natures", "vases", "punt"], "mnvp\nuaau\nmtsn\nmuet\ners \nre  \nys"],
    [["bummers", "loves", "Apple", "darkly"], "blAd\nuopa\nmvpr\nmelk\nesel\nr  y\ns"],
    [["reissue", "mural", "daunts", "Reese"], "rmdR\neuae\nirue\nsans\nslte\nu s \ne"],
    [["gamble", "flubbed", "engulfs", "escorts"], "gfee\nalns\nmugc\nbbuo\nlblr\neeft\n dss"],
    [["soli", "theism", "momma", "sicks"], "stms\nohoi\nlemc\niimk\n sas\n m"],
    [["prewar", "attack", "five", "Pruitt"], "pafP\nrtir\netvu\nwaei\nac t\nrk t"],
    [["Winfred", "tempo", "chile", "finery"], "Wtcf\niehi\nnmin\nfple\nroer\ne  y\nd"],
    [["moaning", "oath", "swops", "Grady"], "mosG\noawr\natoa\nnhpd\ni sy\nn   \ng"],
    [["plaice", "node", "Koreans", "owing"], "pnKo\nloow\nadri\nieen\nc ag\ne n \n  s"],
    [["taints", "ibis", "rod", "zeroing"], "tirz\naboe\niidr\nns o\nt  i\ns  n\n   g"],
    [["certain", "tubs", "card", "wrack"], "ctcw\neuar\nrbra\ntsdc\na  k\ni   \nn"],
    [["flipped", "chichis", "amen", "Russo"], "fcaR\nlhmu\niies\npcns\nph o\nei  \nds"],
    [["wince", "artiste", "sheen", "hill"], "wash\nirhi\nntel\nciel\nesn \n t  \n e"],
    [["Donne", "McLuhan", "removed", "Ptolemy"], "DMrP\nocet\nnLmo\nnuol\nehve\n aem\n ndy"],
    [["bogus", "futz", "pulpits", "alumnae"], "bfpa\nouul\ngtlu\nuzpm\ns in\n  ta\n  se"],
    [["zodiacs", "Togo", "Ashanti", "piazza"], "zTAp\noosi\ndgha\nioaz\na nz\nc ta\ns i"],
    [["tune", "meshes", "symptom", "proceed"], "tmsp\nueyr\nnsmo\nehpc\n ete\n soe\n  md"],
    [["buzzard", "Hebe", "tardier", "vaginal"], "bHtv\nueaa\nzbrg\nzedi\na in\nr ea\nd rl"],
    [["Kazan", "dawdler", "Fulani", "saves"], "KdFs\naaua\nzwlv\nadae\nnlns\n ei \n r"],
    [["last", "thorn", "wieners", "grunge"], "ltwg\nahir\nsoeu\ntrnn\n neg\n  re\n  s"],
    [["Poiret", "Amish", "closure", "effigy"], "PAce\nomlf\niiof\nrssi\nehug\nt ry\n  e"],
    [["dunned", "cloudy", "waked", "duding"], "dcwd\nulau\nnokd\nnuei\neddn\ndy g"],
    [["stem", "bluing", "warps", "ebonies"], "sbwe\ntlab\neuro\nmipn\n nsi\n g e\n   s"],
    [["fulled", "heaven", "healer", "raft"], "fhhr\nueea\nlaaf\nlvlt\neee \ndnr"],
    [["snow", "algebra", "tested", "Aguirre"], "satA\nnleg\nogsu\nweti\n ber\n rdr\n a e"],
    [["Cezanne", "Cepheus", "Horus", "fib"], "CCHf\neeoi\nzprb\nahu \nnes \nnu  \nes"],
    [["occupy", "fishes", "Alice", "ditty"], "ofAd\ncili\ncsit\nuhct\npeey\nys"],
    [["blazing", "funding", "helper", "skirted"], "bfhs\nluek\nanli\nzdpr\niiet\nnnre\ngg d"],
    [["Kristen", "catches", "Huey", "anymore"], "KcHa\nraun\nitey\nscym\nth o\nee r\nns e"],
    [["decoys", "Hanson", "mopes", "untied"], "dHmu\neaon\ncnpt\nosei\nyose\nsn d"],
    [["Camel", "Hoff", "feature", "Ernest"], "CHfE\naoer\nmfan\nefte\nl us\n  rt\n  e"],
    [["robots", "flings", "gables", "meekest"], "rfgm\nolae\nbibe\nonlk\ntgee\nssss\n   t"],
    [["locker", "Orestes", "coccyx", "threats"], "lOct\noroh\ncecr\nksce\netya\nrext\n s s"],
    [["isthmi", "barging", "irately", "count"], "ibic\nsaro\ntrau\nhgtn\nmiet\ninl \n gy"],
    [["manic", "Mondays", "kinking", "airways"], "mMka\naoii\nnnnr\nidkw\ncaia\n yny\n sgs"],
    [["virile", "relates", "unroll", "plunged"], "vrup\nienl\nrlru\niaon\nltlg\neele\n s d"],
    [["Auriga", "beside", "turban", "Chan"], "AbtC\nueuh\nrsra\niibn\ngda \naen"],
    [["joists", "quarrel", "rearms", "fleeces"], "jqrf\nouel\niaae\nsrre\ntrmc\nsese\n l s"],
    [["unhooks", "hereby", "hobbled", "peeping"], "uhhp\nneoe\nhrbe\noebp\nobli\nkyen\ns dg"],
    [["hefted", "heppest", "solder", "owl"], "hhso\neeow\nfpll\ntpd \neee \ndsr \n t"],
    [["enthral", "Jasmine", "adopt", "enclose"], "eJae\nnadn\ntsoc\nhmpl\nrito\nan s\nle e"],
    [["mummers", "error", "newborn", "vassals"], "menv\nurea\nmrws\nmobs\neroa\nr rl\ns ns"],
    [["served", "A", "Tran", "Davids"], "sATD\ne ra\nr av\nv ni\ne  d\nd  s"],
    [["decade", "stated", "Ne", "Cranach"], "dsNC\neter\nca a\nat n\nde a\ned c\n   h"],
    [["Roy", "Tethys", "bowmen", "Roger"], "RTbR\noeoo\nytwg\n hme\n yer\n sn"],
    [["setter", "stamps", "oleo", "alibi"], "ssoa\netll\ntaei\ntmob\nep i\nrs"],
    [["ebbs", "etch", "Elisa", "drums"], "eeEd\nbtlr\nbciu\nshsm\n  as"],
    [["Mojave", "whizzes", "Arieses", "bodes"], "MwAb\nohro\njiid\nazee\nvzss\neee \n ss"],
    [["record", "spanks", "bylines", "mayhem"], "rsbm\nepya\ncaly\nonih\nrkne\ndsem\n  s"],
    [["Ebola", "doers", "Stanton", "winged"], "EdSw\nboti\noean\nlrng\naste\n  od\n  n"],
    [["Biscay", "season", "Bertie", "falsify"], "BsBf\nieea\nsarl\ncsts\naoii\nynef\n   y"],
    [["slumped", "lead", "jingle", "Hunt"], "sljH\nleiu\nuann\nmdgt\np l \ne e \nd"],
    [["lees", "Andorra", "labor", "cent"], "lAlc\nenae\nedbn\nsoot\n rr \n r  \n a"],
    [["kowtows", "diciest", "garble", "damask"], "kdgd\noiaa\nwcrm\ntiba\noels\nwsek\nst"],
    [["nooses", "Carib", "shaykh", "balcony"], "nCsb\noaha\noral\nsiyc\nebko\ns hn\n   y"],
    [["weave", "endings", "Bryant", "hoummos"], "weBh\nenro\nadyu\nviam\nennm\n gto\n s s"],
    [["Huggins", "Lou", "tinkled", "chemist"], "HLtc\nuoih\ngune\ng km\ni li\nn es\ns dt"],
    [["tubed", "Jew", "tissues", "linings"], "tJtl\nueii\nbwsn\ne si\nd un\n  eg\n  ss"],
    [["viragos", "sir", "zingers", "oaf"], "vszo\niiia\nrrnf\na g \ng e \no r \ns s"],
    [["jazzes", "Gates", "Nile", "Toyota"], "jGNT\naaio\nztly\nzeeo\nes t\ns  a"],
    [["goatees", "Molotov", "global", "Mattel"], "gMgM\noola\nalot\ntobt\netae\neoll\nsv"],
    [["lesions", "climber", "vital", "painted"], "lcvp\nelia\nsiti\niman\noblt\nne e\nsr d"],
    [["love", "recta", "purees", "faddish"], "lrpf\noeua\nvcrd\neted\n aei\n  ss\n   h"],
    [["hugged", "Christi", "toppled", "Samsung"], "hCtS\nuhoa\ngrpm\ngips\neslu\ndten\n idg"],
    [["nickels", "Utrillo", "Irkutsk", "Taine"], "nUIT\nitra\ncrki\nkiun\nelte\nlls \nsok"],
    [["pilau", "libidos", "akin", "Velez"], "plaV\niike\nlbil\naine\nud z\n o  \n s"],
    [["sticks", "boring", "Lopez", "descry"], "sbLd\ntooe\nirps\nciec\nknzr\nsg y"],
    [["Salton", "lowers", "larder", "relay"], "Sllr\naoae\nlwrl\nteda\norey\nnsr"],
    [["blowup", "sunrise", "nowise", "gun"], "bsng\nluou\nonwn\nwri \nuis \npse \n e"],
    [["Britt", "Albion", "kinetic", "tallied"], "BAkt\nrlia\nibnl\ntiel\ntoti\n nie\n  cd"],
    [["Gill", "insults", "blowup", "Lagos"], "GibL\ninla\nlsog\nluwo\n lus\n tp \n s"],
    [["grimed", "varmint", "fiction", "perish"], "gvfp\nraie\nircr\nmmti\neiis\ndnoh\n tn"],
    [["roe", "consist", "asking", "carafes"], "rcac\noosa\nenkr\n sia\n inf\n sge\n t s"],
    [["manhunt", "McQueen", "elide", "wedge"], "mMew\nacle\nnQid\nhudg\nueee\nne  \ntn"],
    [["wadding", "giggled", "booze", "anklet"], "wgba\naion\ndgok\ndgzl\nilee\nne t\ngd"],
    [["alien", "eerie", "jalopy", "Taurus"], "aejT\nleaa\nirlu\neior\nnepu\n  ys"],
    [["floored", "podia", "wobbled", "Goethe"], "fpwG\nlooo\nodbe\noibt\nralh\ne ee\nd d"],
    [["dieting", "wrought", "addles", "coked"], "dwac\nirdo\neodk\ntule\niged\nnhs \ngt"],
    [["abuzz", "gipsy", "honks", "wincing"], "aghw\nbioi\nupnn\nzskc\nzysi\n   n\n   g"],
    [["groaned", "Munoz", "fetlock", "Min"], "gMfM\nruei\nontn\naol \nnzo \ne c \nd k"],
    [["Trieste", "pickier", "recoup", "sconces"], "Tprs\nriec\nicco\nekon\nsiuc\ntepe\ner s"],
    [["lays", "doles", "Deity", "Ghats"], "ldDG\naoeh\nylia\nsett\n sys"],
    [["shears", "loges", "term", "liaise"], "sltl\nhoei\negra\naemi\nrs s\ns  e"],
    [["hide", "osiers", "flowery", "clung"], "hofc\nisll\ndiou\neewn\n reg\n sr \n  y"],
    [["notched", "irked", "takings", "sorts"], "nits\norao\ntkkr\nceit\nhdns\ne g \nd s"],
    [["wriggly", "Sonia", "erupts", "myrtles"], "wSem\nrory\ninur\ngipt\ngatl\nl se\ny  s"],
    [["knave", "jib", "firearm", "Mayer"], "kjfM\nniia\nabry\nv ee\ne ar\n  r \n  m"],
    [["fixes", "Joshua", "ported", "stomach"], "fJps\nioot\nxsro\nehtm\nsuea\n adc\n   h"],
    [["seducer", "wales", "flanges", "Foreman"], "swfF\nealo\ndlar\nuene\ncsgm\ne ea\nr sn"],
    [["Oberlin", "piggies", "pulley", "unhands"], "Oppu\nbiun\neglh\nrgla\nlien\nieyd\nns s"],
    [["boat", "quill", "clean", "cassock"], "bqcc\noula\naies\ntlas\n lno\n   c\n   k"],
    [["Aiken", "feral", "piques", "goal"], "Afpg\nieio\nkrqa\neaul\nnle \n  s"],
    [["roans", "bisect", "Edwardo", "swiped"], "rbEs\noidw\naswi\nneap\nscre\n tdd\n  o"],
    [["reckons", "grow", "hobby", "catnip"], "rghc\neroa\ncobt\nkwbn\no yi\nn  p\ns"],
    [["Exocet", "leather", "newsmen", "expanse"], "Elne\nxeex\noawp\nctsa\nehmn\ntees\n rne"],
    [["Anselmo", "jobbing", "dippers", "Whigs"], "AjdW\nnoih\nsbpi\nebpg\nlies\nmnr \nogs"],
    [["tun", "boobed", "coups", "unmoral"], "tbcu\nuoon\nnoum\n bpo\n esr\n d a\n   l"],
    [["accost", "peseta", "simper", "lasted"], "apsl\nceia\ncsms\noept\nstee\ntard"],
    [["instal", "prying", "defense", "corked"], "ipdc\nnreo\nsyfr\ntiek\nanne\nlgsd\n  e"],
    [["edgings", "refills", "lambast", "goofed"], "erlg\ndeao\ngfmo\niibf\nnlae\nglsd\nsst"],
    [["Morton", "joiners", "Campos", "freeing"], "MjCf\nooar\nrime\ntnpe\noeoi\nnrsn\n s g"],
    [["poultry", "Vaduz", "hampers", "England"], "pVhE\noaan\nudmg\nlupl\ntzea\nr rn\ny sd"],
    [["wooding", "lustre", "Chester", "Talmuds"], "wlCT\nouha\nosel\ndtsm\nirtu\nneed\ng rs"],
    [["psyche", "acting", "Stacie", "Suwanee"], "paSS\nsctu\nytaw\ncica\nhnin\negee\n   e"],
    [["eke", "palls", "vaguer", "period"], "epvp\nkaae\nelgr\n lui\n seo\n  rd"],
    [["cellars", "r", "ricked", "sprier"], "crrs\ne ip\nl cr\nl ki\na ee\nr dr\ns"],
    [["pianos", "amoral", "cavil", "slur"], "pacs\nimal\naovu\nnrir\noal \nsl"],
    [["titters", "liker", "bossier", "limbos"], "tlbl\niioi\ntksm\ntesb\nerio\nr es\ns r"],
    [["child", "drywall", "smelter", "sarong"], "cdss\nhrma\niyer\nlwlo\ndatn\n leg\n lr"],
    [["overdo", "bussing", "butte", "topping"], "obbt\nvuuo\nestp\nrstp\ndiei\non n\n g g"],
    [["volt", "Johanna", "key", "diciest"], "vJkd\nooei\nlhyc\nta i\n n e\n n s\n a t"],
    [["puzzle", "iced", "pompons", "stings"], "pips\nucot\nzemi\nzdpn\nl og\ne ns\n  s"],
    [["marrow", "goad", "racily", "locus"], "mgrl\naoao\nracc\nrdiu\no ls\nw y"],
    [["dunking", "dork", "ruled", "evince"], "ddre\nuouv\nnrli\nkken\ni dc\nn  e\ng"],
    [["hoodlum", "Ferris", "direst", "Gonzalo"], "hFdG\noeio\norrn\ndrez\nlisa\nustl\nm  o"],
    [["unearth", "suction", "Chloe", "allay"], "usCa\nnuhl\necll\natoa\nriey\nto  \nhn"],
    [["counter", "Coward", "shaping", "cosigns"], "cCsc\nooho\nuwas\nnapi\ntrig\nednn\nr gs"],
    [["exhale", "knavish", "diatom", "foist"], "ekdf\nxnio\nhaai\navts\nliot\nesm \n h"],
    [["liaison", "trimmer", "finis", "Barron"], "ltfB\niria\nainr\nimir\nsmso\noe n\nnr"],
    [["peptic", "hiked", "Ojibwas", "berg"], "phOb\neije\npkir\ntebg\nidw \nc a \n  s"],
    [["snarled", "mite", "ski", "jukebox"], "smsj\nniku\natik\nre e\nl  b\ne  o\nd  x"],
    [["ruining", "dotted", "dances", "trail"], "rddt\nuoar\nitna\nntci\nieel\nnds \ng"],
    [["bye", "crushes", "manners", "husky"], "bcmh\nyrau\neuns\n snk\n hey\n er \n ss"],
    [["Libya", "Shrek", "anyhow", "urns"], "LSau\nihnr\nbryn\nyehs\nako \n  w"],
    [["danker", "kidded", "dis", "Cannon"], "dkdC\naiia\nndsn\nkd n\nee o\nrd n"],
    [["avenues", "Darin", "clique", "geld"], "aDcg\nvale\neril\nniqd\nunu \ne e \ns"],
    [["meowed", "bellied", "middles", "Pierrot"], "mbmP\neeii\nolde\nwldr\neilr\ndeeo\n dst"],
    [["fueled", "homeboy", "drably", "feting"], "fhdf\nuore\nemat\nlebi\nebln\ndoyg\n y"],
    [["fangs", "haired", "led", "Spock"], "fhlS\naaep\nnido\ngr c\nse k\n d"],
    [["fragile", "outrage", "settee", "Indira"], "fosI\nruen\nattd\ngrti\niaer\nlgea\nee"],
    [["Mays", "Grundy", "licking", "synod"], "MGls\nariy\nyucn\nsnko\n did\n yn \n  g"],
    [["ices", "gigging", "terry", "figured"], "igtf\nciei\negrg\nsgru\n iyr\n n e\n g d"],
    [["cyclic", "summits", "shirked", "Jewell"], "cssJ\nyuhe\ncmiw\nlmre\niikl\nctel\n sd"],
    [["hilt", "annoys", "prowl", "rebinds"], "hapr\ninre\nlnob\ntowi\n yln\n s d\n   s"],
    [["howls", "denser", "pickets", "sponger"], "hdps\noeip\nwnco\nlskn\nseeg\n rte\n  sr"],
    [["fortes", "Masonic", "veils", "Blevins"], "fMvB\noael\nrsie\ntolv\nensi\nsi n\n c s"],
    [["urgent", "Jarred", "hiss", "stripes"], "uJhs\nrait\ngrsr\nersi\nne p\ntd e\n   s"],
    [["apply", "cotter", "eave", "cheeky"], "acec\npoah\nptve\nltee\nye k\n r y"],
    [["erupt", "guess", "Wanda", "away"], "egWa\nruaw\nuena\npsdy\ntsa"],
    [["impala", "silos", "sluing", "tickled"], "isst\nmili\npluc\naoik\nlsnl\na ge\n   d"],
    [["Maris", "bawdily", "Harrods", "moronic"], "MbHm\naaao\nrwrr\nidro\nsion\n ldi\n ysc"],
    [["Castor", "Wimsey", "redneck", "grassed"], "CWrg\naier\nsmda\ntsns\noees\nryce\n  kd"],
    [["Seurat", "spans", "slag", "gulf"], "Sssg\neplu\nuaal\nrngf\nas  \nt"],
    [["Nazisms", "scar", "napalms", "podded"], "Nsnp\nacao\nzapd\nirad\ns le\nm md\ns s"],
    [["dominos", "Cajuns", "ponchos", "Galahad"], "dCpG\noaoa\nmjnl\niuca\nnnhh\nosoa\ns sd"],
    [["upload", "vocally", "Jerri", "plaques"], "uvJp\npoel\nlcra\noarq\naliu\ndl e\n y s"],
    [["intros", "exerts", "squirmy", "droops"], "iesd\nnxqr\nteuo\nrrio\notrp\nssms\n  y"],
    [["input", "rascals", "Hershel", "sin"], "irHs\nnaei\npsrn\nucs \ntah \n le \n sl"],
    [["spidery", "nearly", "tilting", "shimmer"], "snts\npeih\niali\ndrtm\nelim\nryne\ny gr"],
    [["papers", "shearer", "Annam", "warned"], "psAw\nahna\npenr\neaan\nrrme\nse d\n r"],
    [["hoagies", "feudal", "candle", "unseat"], "hfcu\noean\nauns\ngdde\niala\nelet\ns"],
    [["viceroy", "sunny", "perming", "paps"], "vspp\niuea\ncnrp\nenms\nryi \no n \ny g"],
    [["clue", "jetting", "Sextans", "spar"], "cjSs\nleep\nutxa\nettr\n ia \n nn \n gs"],
    [["pajamas", "cured", "oblate", "rends"], "pcor\naube\njrln\naead\nmdts\na e \ns"],
    [["roped", "belling", "volleys", "cudgel"], "rbvc\noeou\nplld\nellg\ndiee\n nyl\n gs"],
    [["leaved", "Abelard", "Rizal", "abreast"], "lARa\nebib\naezr\nvlae\neala\ndr s\n d t"],
    [["catkin", "inject", "Miles", "risking"], "ciMr\nanii\ntjls\nkeek\nicsi\nnt n\n   g"],
    [["riffing", "Lemuel", "beasts", "indices"], "rLbi\nieen\nfmad\nfusi\nietc\nnlse\ng  s"],
    [["litmus", "nits", "Hampton", "siring"], "lnHs\niiai\nttmr\nmspi\nu tn\ns og\n  n"],
    [["pilafs", "Rachael", "singled", "lobs"], "pRsl\niaio\nlcnb\nahgs\nfal \nsee \n ld"],
    [["tampon", "limes", "gross", "potting"], "tlgp\nairo\nmmot\npest\nossi\nn  n\n   g"],
    [["weaned", "godless", "plotted", "seep"], "wgps\neole\nadoe\nnltp\neet \ndse \n sd"],
    [["smelt", "dormer", "cold", "Crowley"], "sdcC\nmoor\nerlo\nlmdw\nte l\n r e\n   y"],
    [["fevers", "Booth", "Bond", "insulin"], "fBBi\neoon\nvons\netdu\nrh l\ns  i\n   n"],
    [["blowzy", "vended", "folding", "sages"], "bvfs\nleoa\nonlg\nwdde\nzeis\nydn \n  g"],
    [["bulks", "Pepin", "finely", "ruin"], "bPfr\nueiu\nlpni\nkien\nsnl \n  y"],
    [["inroad", "joule", "swerved", "commute"], "ijsc\nnowo\nruem\nolrm\naevu\nd et\n  de"],
    [["majesty", "Niger", "smelled", "fizzled"], "mNsf\naimi\njgez\neelz\nsrll\nt ee\ny dd"],
    [["Sachs", "denials", "Frankie", "limited"], "SdFl\naeri\ncnam\nhini\nsakt\n lie\n sed"],
    [["crow", "Spenser", "staffer", "sanding"], "cSss\nrpta\noean\nwnfd\n sfi\n een\n rrg"],
    [["reaming", "Fremont", "cruet", "exiling"], "rFce\nerrx\naeui\nmmel\nioti\nnn n\ngt g"],
    [["Witt", "vetches", "Fitzroy", "perils"], "WvFp\nieie\ntttr\ntczi\n hrl\n eos\n sy"],
    [["Connery", "homage", "carols", "Sinatra"], "ChcS\nooai\nnmrn\nnaoa\neglt\nresr\ny  a"],
    [["incest", "became", "whom", "Nubia"], "ibwN\nnehu\nccob\neami\nsm a\nte"],
    [["Lansing", "spunk", "pieces", "inn"], "Lspi\napin\nnuen\nsnc \nike \nn s \ng"],
    [["goutier", "android", "servo", "brothel"], "gasb\noner\nudro\ntrvt\niooh\nei e\nrd l"],
    [["lighten", "forever", "Soho", "fooling"], "lfSf\niooo\ngrho\nheol\ntv i\nee n\nnr g"],
    [["jog", "hyenas", "moss", "scuba"], "jhms\noyoc\ngesu\n nsb\n a a\n s"],
    [["Faeroe", "Eliot", "kindles", "reins"], "FEkr\nalie\neini\nrodn\notls\ne e \n  s"],
    [["pitying", "stymies", "nun", "curs"], "psnc\nituu\ntynr\nym s\nii  \nne  \ngs"],
    [["whinier", "drugged", "jail", "spender"], "wdjs\nhrap\niuie\nngln\nig d\nee e\nrd r"],
    [["mating", "nope", "Verne", "Laplace"], "mnVL\naoea\ntprp\nienl\nn ea\ng  c\n   e"],
    [["earth", "ironing", "linked", "perched"], "eilp\narie\nronr\ntnkc\nhieh\n nde\n g d"],
    [["betaken", "skirt", "ems", "stalls"], "bses\nekmt\ntisa\nar l\nkt l\ne  s\nn"],
    [["refutes", "Palmyra", "fever", "vaginae"], "rPfv\neaea\nflvg\numei\ntyrn\ner a\nsa e"],
    [["spoons", "prices", "Kristie", "bimbos"], "spKb\nprri\noiim\nocsb\nneto\nssis\n  e"],
    [["gringos", "junco", "lastly", "flubbed"], "gjlf\nrual\ninsu\nnctb\ngolb\no ye\ns  d"],
    [["cared", "spite", "hurdler", "gushed"], "cshg\napuu\nrirs\netdh\ndele\n  ed\n  r"],
    [["off", "gainsay", "finale", "salad"], "ogfs\nfaia\nfinl\n naa\n sld\n ae \n y"],
    [["flavor", "barrio", "bats", "waylaid"], "fbbw\nlaaa\narty\nvrsl\noi a\nro i\n   d"],
    [["Lamar", "scalars", "Mauro", "aver"], "LsMa\nacav\nmaue\nalrr\nrao \n r  \n s"],
    [["Clorox", "China", "bless", "Ursula"], "CCbU\nlhlr\noies\nrnsu\noasl\nx  a"],
    [["alloyed", "Luria", "Kenyan", "fuchsia"], "aLKf\nlueu\nlrnc\noiyh\nyaas\ne ni\nd  a"],
    [["autism", "Nashua", "zinger", "duchies"], "aNzd\nuaiu\ntsnc\nihgh\nsuei\nmare\n   s"],
    [["selves", "donkeys", "locket", "infancy"], "sdli\neoon\nlncf\nvkka\neeen\nsytc\n s y"],
    [["realign", "Sheryl", "pippins", "pipe"], "rSpp\nehii\naepp\nlrpe\niyi \ngln \nn s"],
    [["misdone", "pasting", "potshot", "Windex"], "mppW\niaoi\nsstn\ndtsd\noihe\nnnox\negt"],
    [["decides", "taxed", "cares", "corsage"], "dtcc\neaao\ncxrr\niees\nddsa\ne  g\ns  e"],
    [["rioted", "livers", "cubicle", "slung"], "rlcs\niiul\novbu\ntein\nercg\ndsl \n  e"],
    [["salad", "Tara", "openers", "least"], "sTol\naape\nlrea\naans\nd et\n  r \n  s"],
    [["dived", "enrol", "Bonn", "aqua"], "deBa\ninoq\nvrnu\neona\ndl"],
    [["fiscals", "corrals", "largely", "homily"], "fclh\nioao\nsrrm\ncrgi\naael\nllly\nssy"],
    [["swifter", "moraine", "carping", "sorted"], "smcs\nwoao\nirrr\nfapt\ntiie\nennd\nreg"],
    [["railing", "gills", "neater", "jitney"], "rgnj\naiei\nilat\nlltn\nisee\nn ry\ng"],
    [["sterns", "Gonzalo", "members", "tip"], "sGmt\ntoei\nenmp\nrzb \nnae \nslr \n os"],
    [["hostler", "parting", "feasted", "solvent"], "hpfs\noaeo\nsral\nttsv\nlite\nenen\nrgdt"],
    [["raffled", "three", "convoy", "coy"], "rtcc\nahoo\nfrny\nfev \nleo \ne y \nd"],
    [["Wylie", "warn", "idiom", "ravish"], "Wwir\nyada\nlriv\ninoi\ne ms\n   h"],
    [["wetland", "lubed", "Bernays", "lefty"], "wlBl\neuee\ntbrf\nlent\naday\nn y \nd s"],
    [["Dewitt", "crane", "glens", "relates"], "Dcgr\nerle\nwael\ninna\ntest\nt  e\n   s"],
    [["murkier", "grave", "erring", "ice"], "mgei\nurrc\nrare\nkvi \nien \ne g \nr"],
    [["Dorian", "Whitley", "hastes", "sworn"], "DWhs\nohaw\nriso\nittr\nalen\nnes \n y"],
    [["oversee", "idiotic", "wars", "footed"], "oiwf\nvdao\neiro\nrost\nst e\nei d\nec"],
    [["reefing", "Torah", "Janell", "rote"], "rTJr\neoao\nernt\nfaee\nihl \nn l \ng"],
    [["syphon", "shown", "gesture", "hissed"], "ssgh\nyhei\nposs\nhwts\nonue\nn rd\n  e"],
    [["wiriest", "weepy", "archway", "samovar"], "wwas\niera\nrecm\nipho\neywv\ns aa\nt yr"],
    [["shaver", "drummed", "fiction", "Ionics"], "sdfI\nhrio\naucn\nvmti\nemic\nreos\n dn"],
    [["lankest", "shacks", "dwelled", "Peg"], "lsdP\nahwe\nnaeg\nkcl \nekl \nsse \nt d"],
    [["gunnery", "mottle", "smoky", "routed"], "gmsr\nuomo\nntou\nntkt\nelye\nre d\ny"],
    [["bagged", "sundown", "rosily", "Audra"], "bsrA\nauou\ngnsd\ngdir\neola\ndwy \n n"],
    [["zone", "sprain", "amoeba", "pH"], "zsap\nopmH\nnro \neae \n ib \n na"],
    [["Ne", "idols", "decorum", "worn"], "Nidw\nedeo\n ocr\n lon\n sr \n  u \n  m"],
    [["rhombi", "trailed", "pagan", "diggers"], "rtpd\nhrai\noagg\nmiag\nblne\nie r\n d s"],
    [["rupee", "glyph", "tenders", "ascot"], "rgta\nules\npync\nepdo\nehet\n  r \n  s"],
    [["Morphy", "Whitman", "dis", "gel"], "MWdg\nohie\nrisl\npt  \nhm  \nya  \n n"],
    [["cagey", "beloved", "cruet", "foaming"], "cbcf\naero\nglua\neoem\nyvti\n e n\n d g"],
    [["Marquis", "boor", "arose", "squeaks"], "Mbas\naorq\nroou\nqrse\nu ea\ni  k\ns  s"],
    [["Ln", "blitz", "airmail", "pages"], "Lbap\nnlia\n irg\n tme\n zas\n  i \n  l"],
    [["clocks", "Nunki", "Boeing", "knifed"], "cNBk\nluon\nonei\nckif\nkine\ns gd"],
    [["failure", "pulps", "hatchet", "simmers"], "fphs\nauai\niltm\nlpcm\nushe\nr er\ne ts"],
    [["croup", "Sculley", "billets", "Lubbock"], "cSbL\nrciu\noulb\nullb\npleo\n etc\n ysk"],
    [["forayed", "twaddle", "Avalon", "nears"], "ftAn\nowve\nraaa\nadlr\nydos\neln \nde"],
    [["scud", "host", "Ringo", "flirts"], "shRf\ncoil\nusni\ndtgr\n  ot\n   s"],
    [["Delia", "lobbed", "cushy", "yore"], "Dlcy\neouo\nlbsr\nibhe\naey \n d"],
    [["timbre", "brief", "typhus", "flaxen"], "tbtf\niryl\nmipa\nbehx\nrfue\ne sn"],
    [["bones", "Araceli", "bewitch", "convex"], "bAbc\noreo\nnawn\neciv\nsete\n lcx\n ih"],
    [["dingo", "spireas", "riled", "annual"], "dsra\nipin\nniln\ngreu\noeda\n a l\n s"],
    [["jowl", "flap", "cobalt", "Oregon"], "jfcO\nolor\nwabe\nlpag\n  lo\n  tn"],
    [["yeses", "Iva", "rowdy", "Nicaea"], "yIrN\nevoi\nsawc\ne da\ns ye\n   a"],
    [["plank", "earwig", "convene", "warship"], "pecw\nlaoa\narnr\nnwvs\nkieh\n gni\n  ep"],
    [["degrade", "wrens", "fiddly", "Battle"], "dwfB\neria\ngedt\nrndt\nasll\nd ye\ne"],
    [["gabble", "giants", "burred", "twiggy"], "ggbt\naiuw\nbari\nbnrg\nlteg\nesdy"],
    [["Masons", "bitches", "dyes", "actors"], "Mbda\naiyc\nstet\nocso\nnh r\nse s\n s"],
    [["encamp", "shirted", "unbends", "Idaho"], "esuI\nnhnd\nciba\nareh\nmtno\nped \n ds"],
    [["endives", "Apollos", "Tuesday", "grimier"], "eATg\nnpur\ndoei\nilsm\nvldi\neoae\nssyr"],
    [["rubier", "factual", "money", "lisps"], "rfml\nuaoi\nbcns\nitep\neuys\nra  \n l"],
    [["moldy", "Della", "matzoth", "kens"], "mDmk\noeae\nlltn\ndlzs\nyao \n  t \n  h"],
    [["veneers", "savanna", "Nolan", "Marisol"], "vsNM\neaoa\nnvlr\neaai\nenns\nrn o\nsa l"],
    [["slinky", "witty", "Sundas", "drunk"], "swSd\nliur\nitnu\nntdn\nkyak\ny s"],
    [["miff", "foundry", "Dec", "Jerald"], "mfDJ\nioee\nfucr\nfn a\n d l\n r d\n y"],
    [["pshaws", "yawning", "octane", "prepays"], "pyop\nsacr\nhwte\nanap\nwina\nsney\n g s"],
    [["sarcasm", "Naples", "amply", "gofers"], "sNag\naamo\nrppf\nclle\naeyr\nss s\nm"],
    [["prated", "Roget", "peevish", "lucks"], "pRpl\nroeu\nagec\ntevk\netis\nd s \n  h"],
    [["sieves", "soundly", "peons", "lilt"], "sspl\nioei\neuol\nvnnt\neds \nsl  \n y"],
    [["woven", "markets", "mizzen", "fiercer"], "wmmf\noaii\nvrze\nekzr\nneec\n tne\n s r"],
    [["zither", "ragging", "Romulus", "founder"], "zrRf\niaoo\ntgmu\nhgun\neild\nrnue\n gsr"],
    [["pendant", "sooner", "surmise", "marsh"], "pssm\neoua\nnorr\ndnms\naeih\nnrs \nt e"],
    [["birded", "singer", "spines", "redraw"], "bssr\niipe\nrnid\ndgnr\neeea\ndrsw"],
    [["eyed", "Sony", "drastic", "Sharon"], "eSdS\nyorh\nenaa\ndysr\n  to\n  in\n  c"],
    [["nuance", "dangles", "toy", "snorted"], "ndts\nuaon\nanyo\nng r\ncl t\nee e\n s d"],
    [["dirtied", "creels", "takings", "lone"], "dctl\nirao\nrekn\nteie\niln \nesg \nd s"],
    [["dodders", "squirmy", "booth", "squaw"], "dsbs\noqoq\nduou\ndita\nerhw\nrm  \nsy"],
    [["Anacin", "Mohamed", "Taiwan", "zing"], "AMTz\nnoai\nahin\ncawg\nima \nnen \n d"],
    [["jimmy", "head", "clipt", "Husserl"], "jhcH\nielu\nmais\nmdps\ny te\n   r\n   l"],
    [["ghetto", "airhead", "ruddy", "liberty"], "garl\nhiui\nerdb\nthde\nteyr\noa t\n d y"]
  ]

  (CASES + RANDOM_CASES.sample(10)).each do |args, result|
    it "returns #{result} to param #{args}" do
      expect(@executor.execute(*args)).to eq result
    end
  end
end
